### ISSUE TITLE
Supported Elixir versions?

### ISSUE THREAD

**Issue by mikko-kepit** [cadebward/hls#8]
In mix.exs Elixir version value is "~> 1.6" but `HLS.Segment.Tiles` uses `Kernel.then()` which was introduced in 1.12.0. https://github.com/cadebward/hls/blob/master/lib/hls/segment_tiles.ex#L39

Maybe update mix.exs? Or find way to achieve same result with method that works in versions after 1.6.

**Comment by cadebward** [comment]
removed Kernel.then in https://github.com/cadebward/hls/commit/0aaa4be011e8a1e71373cf05bbbf8d3c1397550c and published 0.0.9.
