### ISSUE TITLE
Parse and serialize `EXT-X-MAP` tags

### ISSUE THREAD

**Issue by samrat** [cadebward/hls#9]
Thank you for this library!

For HLS streams using fMP4 files the `EXT-X-MAP` tag is used to specify the path of the mp4 files with the initialization information.

This library doesn't seem to parse or serialize these tags.

I took a stab at implementing this and made some progress but wasn't sure how to handle the [following part of the RFC](https://datatracker.ietf.org/doc/html/rfc8216#page-17):

> It applies to every Media Segment that appears after it in the Playlist until the next EXT-X-MAP tag or until the end of the Playlist.

Are there other tags implemented that I could look at?

**Comment by cadebward** [comment]
Hey @samrat, you are right that we haven't implemented that. I haven't yet seen, in practice at least, more than one `EXT-X-MAP` tag in a playlist, have you?

If you want to take a stab at it, it might be sufficient to get it working according to `until the end of the Playlist` and maybe ignore `until the next EXT-X-MAP tag`. As you can see, we didn't really build this library to account for every single thing in the spec. Mostly just the basics to satisfy our needs.
